name: built_path
version: 0.1.1
description: >-
  Process SVG Path data into Flutter Path objects
  using build_runner.

author: Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/flutter_built_path

environment:
  sdk: '>=2.0.0-dev <3.0.0'
  # flutter: ">=0.5.1 <2.0.0"

dependencies:
  analyzer: ^0.41.2
  build: ^1.6.1
  built_path_annotations:
    git:
      url: git://github.com/nicoPil/flutter_built_path.git
      path: built_path_annotations
  # built_path_annotations:
  # path: ../built_path_annotations
  path_parsing: ^0.1.2
  source_gen: ^0.9.0
  # flutter:
  #   sdk: flutter

dev_dependencies:
  build_config: ^0.4.5
  build_runner: ^1.11.0
  build_test: ^1.3.4
  test: '>=0.12.34 <1.0.0'
